import { useEffect, useId, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import type { ModalState, Workspace } from './model';
import { applyForm, bookingEditable, bookingStarts, bookingEnds, canView, DRAFTS, eventEditable, fields, leader, member, mutate, name, requireMember, resetModel, room, same, stamp, statuses, time, minutes, today, uid, url, users, workspace, writable, writeLocal } from './model';
import { Area, Checks, Empty, Field, Icon, IconButton, Select } from './ui';
import type { ViewProps } from './ui';

function ActivityTile({ activity: x, label, close }: { activity: Workspace; label: string; close: () => void }) {
  const id = useId().replace(/[^a-zA-Z0-9_-]/g, ''), anchor = `--activity-${id}`;
  const name = useRef<HTMLSpanElement>(null), tooltip = useRef<HTMLSpanElement>(null);
  function show() {
    const text = name.current;
    if (text && (text.scrollHeight > text.clientHeight || text.scrollWidth > text.clientWidth)) {
      tooltip.current?.closest('.activity-picker')?.querySelectorAll<HTMLElement>('.activity-tooltip:popover-open').forEach(el => el.hidePopover());
      tooltip.current?.showPopover();
    }
  }
  function hide() { tooltip.current?.hidePopover(); }
  return <a className="activity-tile" href={url(x)} aria-label={`${x.name} · ${label}`} style={{ anchorName: anchor } as CSSProperties}
    onMouseEnter={show} onMouseLeave={event => { if (!event.currentTarget.matches(':focus-visible')) hide(); }}
    onFocus={show} onBlur={event => { if (!event.currentTarget.matches(':hover')) hide(); }}
    onClick={close}>
    <span className={`workspace-initial ${x.type}`}>{x.initial}</span><span ref={name} className="activity-name">{x.name}</span>
    <span ref={tooltip} role="tooltip" popover="manual" className="activity-tooltip" style={{ positionAnchor: anchor } as CSSProperties}>{x.name}</span>
  </a>;
}

export default function Dialog({ model: m, session: s, prefs: p, setPrefs, open, notify, state, close, done }: ViewProps & { state: ModalState; close: () => void; done: (state: ModalState, result?: string | number) => void }) {
  const { kind, id: target, groupId } = state;
  const e = m.events.find(e => same(e.id, target)), b = m.bookings.find(b => same(b.id, target)), r = room(m, target);
  const w = workspace(m, state.workspaceId || (kind.startsWith('booking') ? b?.workspaceId : kind.startsWith('room') ? r?.workspaceId : undefined));
  const allowed = m.workspaces.filter(x => writable(x, s));
  const bookingActivities = m.workspaces.filter(x => writable(x, s) || s.officer && x.status !== '보관');
  const [chosenActivity, setActivity] = useState(String(kind === 'event' && e ? e.workspaceId ?? 'club' : kind === 'booking' && b ? b.workspaceId : w?.id || allowed[0]?.id || 'club'));
  const chosen = workspace(m, chosenActivity), candidates = chosenActivity === 'club' ? users.map(u => u.id) : chosen?.memberIds || [];
  const [assignees, setAssignees] = useState(e?.assigneeIds.length ? e.assigneeIds : candidates.includes(s.userId) ? [s.userId] : [candidates[0]].filter(Boolean));
  const [visibility, setVisibility] = useState(e?.visibility || (chosenActivity === 'club' ? 'club' : 'workspace'));
  const [selectedMembers, setMembers] = useState(kind === 'room' ? r?.memberIds || [s.userId] : w?.memberIds || [s.userId]);
  const [newLeader, setLeader] = useState(w?.leaderId || s.userId);
  const [error, setError] = useState(''), dialog = useRef<HTMLDialogElement>(null);
  const [searching, setSearching] = useState(false), [activityQuery, setActivityQuery] = useState('');
  const activitySearch = useRef<HTMLInputElement>(null);
  const picking = kind === 'workspace-pick';
  const activities = m.workspaces.filter(x => canView(x, s) && x.name.toLocaleLowerCase().includes(activityQuery.trim().toLocaleLowerCase()));
  const groups = m.tagGroups[String(w?.id)] || [], group = groups.find(g => g.id === groupId);
  const readOnly = kind === 'workspace-edit' ? !leader(w, s.userId) : kind === 'event' && e ? !eventEditable(e, m, s) : false;
  const viewKinds = ['workspace-info', 'workspace-pick', 'room-settings', 'tags', 'booking-info', 'document-pick', 'document-history'];
  const canApply = !viewKinds.includes(kind) && !readOnly && !(kind === 'event' && !e && !allowed.length && !s.officer) && !(kind === 'booking' && !bookingActivities.length);
  useEffect(() => {
    const el = dialog.current;
    const opener = document.activeElement as HTMLElement | null;
    if (picking) { el?.showPopover(); (el?.querySelector('button') as HTMLElement | null)?.focus(); }
    else (el?.querySelector('input:not([type=checkbox]):not(:disabled),select:not(:disabled),textarea:not(:disabled)') as HTMLElement | null)?.focus();
    return () => { if (picking) { el?.hidePopover(); if (document.activeElement === document.body) opener?.focus(); } };
  }, []);
  useEffect(() => { if (searching) activitySearch.current?.focus(); }, [searching]);
  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget), get = (key: string) => String(data.get(key) || '');
    if (picking) return;
    try {
      if (kind === 'profile') { const userId = uid(get('userId')); if (!userId) throw new Error('사용자를 선택해야 함'); setPrefs({ userId, officer: data.has('officer'), scope: 'mine' }); }
      else if (kind === 'list-filters') setPrefs({ listType: get('type'), listField: get('field'), listStatus: get('status'), listOwner: get('owner'), listOrder: get('order') });
      else if (kind === 'calendar-filters') setPrefs({ calendarMine: data.has('mine'), calendarScope: get('scope') || 'mine' });
      else if (kind === 'room-sort') setPrefs({ roomSort: get('sort'), roomSortGroup: get('group') });
      else if (kind === 'reset') { resetModel(); writeLocal(DRAFTS, {}); }
      else { const result = applyForm(state, data, s); done(state, result); notify(kind === 'workspace-apply' ? '참가 신청을 보냈어요. 팀장 승인 후 참여할 수 있어요.' : '변경 적용됨'); return; }
      done(state); if (kind === 'reset') notify('샘플 초기화됨');
    } catch (err) { setError((err as Error).message); }
  }
  function reorder(groupId: string, tagId: string | undefined, delta: number) {
    try { mutate(tagId ? '태그 순서 변경' : '그룹 순서 변경', s, next => { const owner = workspace(next, w?.id); requireMember(owner, s); const list = tagId ? next.tagGroups[owner.id].find(g => g.id === groupId)?.tags : next.tagGroups[owner.id]; if (!list) throw new Error('그룹을 찾을 수 없음'); const i = list.findIndex(x => x.id === (tagId || groupId)), j = i + delta; if (i >= 0 && j >= 0 && j < list.length) [list[i], list[j]] = [list[j], list[i]]; }); } catch (err) { setError((err as Error).message); }
  }
  const title: Record<ModalState['kind'], string> = { 'workspace-info': '활동 상세', 'workspace-apply': '참가 신청', profile: '사용자 미리보기', 'list-filters': '활동 필터 및 정렬', 'calendar-filters': '일정 표시 조건', 'room-sort': '방 정렬', 'workspace-pick': '프로젝트 및 스터디', 'workspace-new': '활동 생성', 'workspace-edit': '활동 정보', members: '구성원 및 팀장 위임', leave: '활동 탈퇴', event: e ? '일정 수정' : '일정 등록', 'event-delete': '일정 삭제', booking: b ? '예약 변경' : '예약 신청', 'booking-info': '예약 상세', 'booking-cancel': '예약 취소', room: r ? '방 수정' : '방 생성', 'room-settings': '방 관리', 'room-archive': '방 보관', tags: '태그 그룹 관리', 'group-new': '태그 그룹 추가', 'group-rename': '그룹 이름 변경', 'tag-new': '태그 추가', 'tag-rename': '태그 이름 변경', 'group-delete': '그룹 삭제', 'tag-delete': '태그 삭제', 'document-pick': '회의록 선택', 'document-history': '최근 저장 이력', reset: '샘플 초기화' };
  let body: React.ReactNode;
  switch (kind) {
    case 'workspace-pick': body = <>{searching && <input ref={activitySearch} className="activity-search" type="search" aria-label="프로젝트 및 스터디 검색" placeholder="활동 이름 검색" value={activityQuery} onChange={e => setActivityQuery(e.target.value)} />}{([['project', '프로젝트'], ['study', '스터디']] as const).map(([type, label]) => { const list = activities.filter(x => x.type === type); return <section className="activity-section" key={type} aria-label={label}><h3>{label}</h3><div className="activity-grid">{list.map(x => <ActivityTile key={x.id} activity={x} label={label} close={close} />)}</div>{!list.length && <p className="note-line">{activityQuery.trim() ? `일치하는 ${label}가 없습니다.` : `등록된 ${label}가 없습니다.`}</p>}</section>; })}</>; break;
    case 'workspace-info': body = w ? <><div className="button-row"><span className={`workspace-initial ${w.type}`}>{w.initial}</span><h3>{w.name}</h3><span className={`tag ${member(w, s.userId) ? 'mine' : 'external'}`}>{member(w, s.userId) ? '참여 중' : w.applicantIds?.includes(s.userId) ? '신청 대기' : '미참여'}</span></div><p className="note-line">{w.type === 'study' ? '스터디' : '프로젝트'} · {w.field} · {w.memberIds.length}명 · {w.status}</p><dl className="activity-details"><dt>팀장</dt><dd>{name(w.leaderId)}</dd><dt>목표</dt><dd>{w.goal || '등록된 목표가 없습니다.'}</dd><dt>기간</dt><dd>{w.startDate || '시작일 미정'} ~ {w.endDate || '마감일 미정'}</dd>{canView(w, s) && <><dt>구성원</dt><dd>{w.memberIds.map(name).join(', ')}</dd><dt>최근 변경</dt><dd>{stamp(w.updatedAt)}</dd></>}</dl></> : <Empty>활동을 찾을 수 없습니다.</Empty>; break;
    case 'workspace-apply': body = w ? <><h3>{w.name}</h3><p className="note-line">{w.type === 'study' ? '스터디' : '프로젝트'} · {w.field} · 팀장 {name(w.leaderId)}</p><p>이 활동에 참가 신청을 보낼까요?</p><p className="note-line">팀장이 신청을 확인하고 구성원으로 추가하면 참여할 수 있어요.</p></> : <Empty>활동을 찾을 수 없습니다.</Empty>; break;
    case 'profile': body = <><Select label="사용자" name="userId" items={users.map(u => [u.id, u.name])} defaultValue={s.userId} /><label className="radio-choice"><input type="checkbox" name="officer" defaultChecked={s.officer} />동아리 임원진</label><p className="note-line">팀장은 생성·위임 관계로 결정됨. 여러 활동의 팀장 겸임 가능함. 이 창은 실제 로그인 기능이 아닌 검토용 도구임</p></>; break;
    case 'list-filters': body = <><Select label="유형" name="type" items={[["all", "모두"], ["project", "프로젝트"], ["study", "스터디"]]} defaultValue={p.listType} /><Select label="분야" name="field" items={[["all", "모두"], ...fields]} defaultValue={p.listField} /><Select label="상태" name="status" items={[["active", "진행 활동"], ["all", "모두"], ...statuses]} defaultValue={p.listStatus} /><Select label="팀장" name="owner" items={[["all", "모두"], ...users.map(u => [u.id, u.name] as [string, string])]} defaultValue={p.listOwner} /><Select label="정렬" name="order" items={[["recent", "최근 변경"], ["name", "이름"], ["deadline", "마감"]]} defaultValue={p.listOrder} /></>; break;
    case 'calendar-filters': body = <><label className="radio-choice"><input type="checkbox" name="mine" defaultChecked={p.calendarMine} />내 담당 일정만 보기</label>{!w && s.officer && <Select label="범위" name="scope" items={[["mine", "내 활동"], ["all", "전체 활동 운영 조회"]]} defaultValue={p.calendarScope} />}</>; break;
    case 'room-sort': body = <><Select label="정렬" name="sort" items={[["recent", "최근 대화"], ["name", "이름"], ["tag", "태그 순서"]]} defaultValue={p.roomSort} /><Select label="기준 그룹" name="group" items={groups.map(g => [g.id, g.name])} defaultValue={p.roomSortGroup || groups[0]?.id} /></>; break;
    case 'workspace-new': case 'workspace-edit': body = <><p className="note-line">{kind === 'workspace-new' ? '생성자가 팀장이 됨. 생성 후 구성원에게 위임 가능함' : `팀장 ${name(w?.leaderId || '')} · 생성자 ${name(w?.createdBy || '')}`}</p><Field label="이름" name="name" defaultValue={w?.name} required maxLength={80} />{kind === 'workspace-new' && <Select label="유형" name="type" items={[["project", "프로젝트"], ["study", "스터디"]]} defaultValue="project" />}<Select label="분야" name="field" items={fields} defaultValue={w?.field || fields[0]} /><Area label="목표" name="goal" value={w?.goal} /><div className="form-grid"><Field label="시작일" name="startDate" type="date" defaultValue={w?.startDate} /><Field label="마감일" name="endDate" type="date" defaultValue={w?.endDate} /></div>{kind === 'workspace-new' ? <><span className="note-line">구성원 · 생성자는 자동 포함됨</span><Checks fieldName="members" ids={users.map(u => u.id)} selected={[s.userId]} /></> : <><Select label="상태" name="status" items={statuses} defaultValue={w?.status} /><p className="note-line">{w?.memberIds.map(name).join(', ')}<br />최근 변경 {stamp(w?.updatedAt)}</p></>}</>; break;
    case 'members': body = <><p className="note-line">{w?.applicantIds?.length ? `참가 신청 대기: ${w.applicantIds.map(name).join(', ')} · 승인할 사람을 구성원으로 선택해주세요.` : '참가 신청 대기 없음'}</p><p className="note-line">팀장 한 명은 반드시 구성원으로 남아야 함. 제외된 구성원은 방·문서 접근권을 잃지만 기록은 보존됨</p><Checks fieldName="members" ids={users.map(u => u.id)} selected={selectedMembers} onChange={setMembers} /><Select label="팀장 위임 대상" name="leader" items={selectedMembers.map(id => [id, name(id)])} value={newLeader} onChange={e => setLeader(e.target.value)} /></>; break;
    case 'event': body = !e && !allowed.length && !s.officer ? <Empty>먼저 활동을 생성하거나 참여해야 함 <button type="button" className="button small" onClick={() => open({ kind: 'workspace-new' })}>활동 생성</button></Empty> : <><Field label="제목" name="title" defaultValue={e?.title} required maxLength={100} /><Select label="활동" name="workspaceId" items={[...allowed.map(w => [w.id, w.name] as [string | number, string]), ...(s.officer || readOnly && e?.workspaceId === null ? [['club', '동아리 전체'] as [string, string]] : []), ...(readOnly && w && !allowed.includes(w) ? [[w.id, w.name] as [string | number, string]] : [])]} value={chosenActivity} onChange={event => { const next = workspace(m, event.target.value), ids = next?.memberIds || users.map(u => u.id); setActivity(event.target.value); setAssignees(ids.includes(s.userId) ? [s.userId] : [ids[0]]); setVisibility(event.target.value === 'club' ? 'club' : 'workspace'); }} /><div className="form-grid"><Field label="시작 날짜" name="date" type="date" defaultValue={e?.date || state.date || today()} required /><Field label="종료 날짜" name="endDate" type="date" defaultValue={e?.endDate || state.date || today()} required /><Field label="시작 시각" name="start" type="time" defaultValue={e?.start || '10:00'} required /><Field label="종료 시각" name="end" type="time" defaultValue={e?.end || '11:00'} required /></div><Select label="공개 범위" name="visibility" items={[["workspace", "활동 구성원"], ["private", "담당자만"], ...(s.officer || readOnly && e?.visibility === 'club' ? [['club', '동아리 전체'] as [string, string]] : [])]} value={visibility} onChange={e => setVisibility(e.target.value)} /><span className="note-line">담당자</span><Checks fieldName="assignees" ids={candidates} selected={assignees} onChange={setAssignees} /><Area label="담당업무" name="work" value={e?.work} /><Select label="진행 상태" name="status" items={['예정', '진행 중', '완료', '보류']} defaultValue={e?.status || '예정'} /></>; break;
    case 'booking': body = !bookingActivities.length ? <Empty>예약 가능한 참여 활동이 없음 <button className="button small" type="button" onClick={() => open({ kind: 'workspace-new' })}>활동 생성</button></Empty> : <><Select label="활동" name="workspaceId" items={bookingActivities.map(w => [w.id, w.name])} defaultValue={b?.workspaceId || w?.id || bookingActivities[0]?.id} /><Field label="날짜" name="date" type="date" min={today()} defaultValue={b?.date || state.date || today()} required /><div className="form-grid"><Select label="시작" name="start" items={bookingStarts} defaultValue={b?.start || state.start || '10:00'} /><Select label="종료" name="end" items={bookingEnds} defaultValue={b?.end || time(minutes(state.start || '10:00') + 30)} /></div><Field label="사용 목적" name="purpose" defaultValue={b?.purpose} required maxLength={160} /><p className="note-line">09:00~24:00 · 30분 단위 · 중복 시 확정되지 않음</p></>; break;
    case 'booking-info': { const full = b && (member(workspace(m, b.workspaceId), s.userId) || s.officer); body = b ? <><h3>{full ? workspace(m, b.workspaceId)?.name : '다른 팀 예약'}</h3><p>{b.date} {b.start}~{b.end} · {b.status}</p>{full ? <p className="note-line">예약자 {name(b.ownerId)}<br />{b.purpose || '목적 미입력'}<br />{b.cancelReason && `취소 사유: ${b.cancelReason}`}</p> : <p className="note-line">예약자 {name(b.ownerId)} · 예약 목적과 활동 정보는 구성원에게 표시됨</p>}</> : <Empty>예약을 찾을 수 없음</Empty>; break; }
    case 'booking-cancel': body = <><Field label="취소 사유" name="reason" required maxLength={160} /><p className="note-line">시간 점유는 해제하고 취소 기록은 보존함</p></>; break;
    case 'room': body = <><Field label="방 이름" name="name" defaultValue={r?.name} required maxLength={80} /><span className="note-line">활동 구성원만 참여 가능함</span><Checks fieldName="members" ids={w?.memberIds || []} selected={r?.memberIds || [s.userId]} />{groups.map(g => <fieldset className="tag-group" key={g.id}><legend>{g.name} · 복수 선택</legend>{g.tags.map(t => <label key={t.id}><input type="checkbox" name="tags" value={t.id} defaultChecked={r?.tagIds.includes(t.id)} />{t.name}</label>)}</fieldset>)}</>; break;
    case 'room-settings': body = <><p className="note-line">{w?.name} · 설정은 메인 공간에서 처리함</p>{m.rooms.filter(r => same(r.workspaceId, w?.id) && member(w, s.userId)).map(r => <div className="tag-order-row" key={r.id}><span>{r.name}{r.archived && ' · 보관'}<small className="muted"> · {r.memberIds.map(name).join(', ')}</small></span><div className="button-row">{writable(w, s) && <><IconButton title="방 수정" onClick={() => open({ kind: 'room', id: r.id, workspaceId: r.workspaceId })} />{r.archived ? <IconButton title="방 복원" icon="history" onClick={() => { try { mutate('방 복원', s, next => { const target = room(next, r.id); requireMember(workspace(next, target?.workspaceId), s); if (target) target.archived = false; }); } catch (err) { setError((err as Error).message); } }} /> : <IconButton title="방 보관" icon="close" onClick={() => open({ kind: 'room-archive', id: r.id, workspaceId: r.workspaceId })} />}</>}</div></div>)}</>; break;
    case 'tags': body = <><p className="note-line">그룹·태그의 이름·순서를 관리함. 삭제는 방의 연결만 제거하고 대화·회의록을 보존함</p>{groups.map((g, i) => <section className="tag-group-management" key={g.id}><div className="toolbar-group"><strong>{g.name}</strong><IconButton title="그룹 순서 위로" icon="up" disabled={!i} onClick={() => reorder(g.id, undefined, -1)} /><IconButton title="그룹 순서 아래로" icon="down" disabled={i === groups.length - 1} onClick={() => reorder(g.id, undefined, 1)} /><IconButton title="그룹 이름 변경" onClick={() => open({ kind: 'group-rename', id: g.id, workspaceId: w?.id })} /><IconButton title="그룹 삭제" icon="close" onClick={() => open({ kind: 'group-delete', id: g.id, workspaceId: w?.id })} /><IconButton title="태그 추가" icon="plus" onClick={() => open({ kind: 'tag-new', groupId: g.id, workspaceId: w?.id })} /></div>{g.tags.map((t, i) => <div className="tag-order-row" key={t.id}><span>{t.name}</span><div className="button-row"><IconButton title="순서 위로" icon="up" disabled={!i} onClick={() => reorder(g.id, t.id, -1)} /><IconButton title="순서 아래로" icon="down" disabled={i === g.tags.length - 1} onClick={() => reorder(g.id, t.id, 1)} /><IconButton title="태그 이름 변경" onClick={() => open({ kind: 'tag-rename', id: t.id, groupId: g.id, workspaceId: w?.id })} /><IconButton title="태그 삭제" icon="close" onClick={() => open({ kind: 'tag-delete', id: t.id, groupId: g.id, workspaceId: w?.id })} /></div></div>)}</section>)}</>; break;
    case 'group-new': case 'group-rename': case 'tag-new': case 'tag-rename': body = <Field label="이름" name="name" required maxLength={60} defaultValue={kind === 'group-rename' ? groups.find(g => same(g.id, target))?.name : kind === 'tag-rename' ? group?.tags.find(t => same(t.id, target))?.name : ''} />; break;
    case 'group-delete': case 'tag-delete': { const ids = kind === 'group-delete' ? groups.find(g => same(g.id, target))?.tags.map(t => t.id) || [] : [String(target)], count = m.rooms.filter(r => same(r.workspaceId, w?.id) && r.tagIds.some(t => ids.includes(t))).length; body = <p>{count}개 방의 태그 연결을 제거함. 방과 기록은 그대로 보존됨</p>; break; }
    case 'document-pick': body = <>{m.rooms.filter(r => same(r.workspaceId, w?.id)).map(r => w && <a className="room-item" key={r.id} href={url(w, 'document', r.id)} onClick={close}>{r.name}{r.archived && ' · 보관'}</a>)}</>; break;
    case 'document-history': body = <>{(m.documentMeta[String(target)]?.history || []).map(h => <details key={h.version}><summary>v{h.version} · {name(h.updatedBy)} · {stamp(h.updatedAt)}</summary><pre className="history-body">{h.body}</pre></details>)}{!m.documentMeta[String(target)]?.history.length && <p>이전 저장 이력 없음</p>}</>; break;
    case 'leave': body = <p>활동과 방 접근권을 잃지만 작성 기록은 유지됨. 팀장은 먼저 위임해야 함</p>; break;
    case 'event-delete': body = <p>이 일정을 삭제 처리함. 변경 기록은 유지됨</p>; break;
    case 'room-archive': body = <p>방 탐색에서 제외하며 대화와 회의록은 유지됨. 방 설정에서 복원 가능함</p>; break;
    case 'reset': body = <p>활동·일정·예약·문서·초안의 현재 변경을 제거하고 샘플로 되돌림</p>; break;
  }
  return <dialog open={picking ? undefined : true} popover={picking ? 'auto' : undefined} id="modal" ref={dialog} className={`main-dialog ${picking ? 'activity-picker' : ''}`} aria-labelledby="modal-title" onKeyDown={event => { if (event.key === 'Escape') { const tips = event.currentTarget.querySelectorAll<HTMLElement>('.activity-tooltip:popover-open'); if (tips.length) { event.preventDefault(); event.stopPropagation(); tips.forEach(el => el.hidePopover()); } } }} onCancel={event => { event.preventDefault(); close(); }} onToggle={event => { if (picking && event.target === event.currentTarget && event.newState === 'closed') close(); }}><form onSubmit={submit}><header className="modal-heading"><h2 id="modal-title">{title[kind]}</h2><div className="modal-heading-actions">{picking && <><button type="button" className="icon-button" title="활동 검색" aria-label="활동 검색" aria-expanded={searching} onClick={() => { setSearching(!searching); setActivityQuery(''); }}><Icon name="search" /></button><IconButton title="프로젝트 및 스터디 생성" icon="plus" onClick={() => open({ kind: 'workspace-new' })} /></>}<IconButton title="닫기" icon="close" onClick={close} /></div></header><div className="modal-body"><fieldset disabled={readOnly} className="form-body">{body}</fieldset>{readOnly && <p className="note-line">조회 전용임</p>}{error && <p className="form-error" role="alert">{error}</p>}</div>{!picking && <footer className="modal-footer">
    {kind === 'workspace-info' && w && <>{canView(w, s) && <a className="button" href={url(w)} onClick={close}>활동 열기</a>}{!member(w, s.userId) && <button className="button primary" type="button" disabled={w.applicantIds?.includes(s.userId) || ['완료', '보관'].includes(w.status)} onClick={() => open({ kind: 'workspace-apply', workspaceId: w.id })}>{w.applicantIds?.includes(s.userId) ? '신청 대기' : ['완료', '보관'].includes(w.status) ? '신청 마감' : '참가 신청'}</button>}</>}
    {kind === 'workspace-edit' && w && (leader(w, s.userId) ? <button type="button" className="button" onClick={() => open({ kind: 'members', workspaceId: w.id })}>구성원 / 위임</button> : member(w, s.userId) && <button type="button" className="button danger" onClick={() => open({ kind: 'leave', workspaceId: w.id })}>탈퇴</button>)}
    {kind === 'event' && e && !readOnly && <button type="button" className="button danger" onClick={() => open({ kind: 'event-delete', id: e.id, workspaceId: e.workspaceId ?? undefined })}>삭제</button>}
    {kind === 'booking-info' && b && b.status !== '취소' && bookingEditable(b, m, s) && <><button type="button" className="button" onClick={() => open({ kind: 'booking', id: b.id, workspaceId: b.workspaceId })}>변경</button><button type="button" className="button danger" onClick={() => open({ kind: 'booking-cancel', id: b.id, workspaceId: b.workspaceId })}>취소</button></>}
    {kind === 'room-settings' && writable(w, s) && <><button type="button" className="button" onClick={() => open({ kind: 'tags', workspaceId: w!.id })}>태그 그룹</button><button type="button" className="button" onClick={() => open({ kind: 'room', workspaceId: w!.id })}>방 생성</button></>}
    {kind === 'tags' && writable(w, s) && <button type="button" className="button" onClick={() => open({ kind: 'group-new', workspaceId: w!.id })}>그룹 추가</button>}
    {canApply && <button className="button primary" type="submit">{kind === 'workspace-apply' ? '신청 보내기' : '적용'}</button>}<button className="button" type="button" onClick={close}>닫기</button>
  </footer>}</form></dialog>;
}


