import { Fragment, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import type { CalendarEvent, Workspace } from './model';
import { bookingEndMinutes, bookingStarts, calendarEvents, canView, dashboardDeadlines, dateObj, dateString, id, iso, member, minutes, mutate, name, requireMember, room, same, stamp, time, today, url, workspace, writable } from './model';
import { Empty, Heading, Icon, IconButton } from './ui';
import type { ViewProps } from './ui';

export function Dashboard({ model: m, session: s, prefs: p, setPrefs, open, logout }: ViewProps & { logout: () => void }) {
  const [query, setQuery] = useState(''), [mine, setMine] = useState(false), [deadlineActivity, setDeadlineActivity] = useState('all');
  const joined = m.workspaces.filter(w => member(w, s.userId));
  const list = m.workspaces.filter(w => (!mine || member(w, s.userId)) && w.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()) && (p.listType === 'all' || w.type === p.listType) && (p.listField === 'all' || w.field === p.listField) && (p.listOwner === 'all' || w.leaderId === p.listOwner) && (p.listStatus === 'all' || (p.listStatus === 'active' ? !['완료', '보관'].includes(w.status) : w.status === p.listStatus))).sort((a, b) => p.listOrder === 'name' ? a.name.localeCompare(b.name, 'ko') : p.listOrder === 'deadline' ? (a.endDate || '9999').localeCompare(b.endDate || '9999') : b.updatedAt.localeCompare(a.updatedAt));
  const deadlines = dashboardDeadlines(m, s), filtered = deadlines.filter(d => deadlineActivity === 'all' || String(d.workspaceId ?? 'club') === deadlineActivity);
  return <div className="home-dashboard">
    <section className="home-panel home-activities" aria-label="전체 활동">
      <header className="home-panel-heading"><div><span className="home-eyebrow">PROJECTS & STUDIES</span><h1>활동</h1><p className="note-line">함께할 활동을 찾아보고 참여하세요.</p></div><IconButton title="활동 생성" icon="plus" onClick={() => open({ kind: 'workspace-new' })} /></header>
      <div className="home-activity-tools"><input className="filter-input" type="search" placeholder="활동 검색" aria-label="활동 검색" value={query} onChange={e => setQuery(e.target.value)} /><IconButton title="필터 및 정렬" icon="filter" onClick={() => open({ kind: 'list-filters' })} /><button className="button quiet small" onClick={() => { setQuery(''); setMine(false); setPrefs({ listType: 'all', listField: 'all', listStatus: 'active', listOwner: 'all', listOrder: 'recent' }); }}>초기화</button></div>
      <div className="home-list-summary"><div className="pill-tabs"><button className={!mine ? 'active' : ''} aria-pressed={!mine} onClick={() => setMine(false)}>전체 활동</button><button className={mine ? 'active' : ''} aria-pressed={mine} onClick={() => setMine(true)}>참여 중</button></div><span className="note-line">{list.length}개 활동</span></div>
      <div className="home-activity-scroll" role="region" aria-label="활동 목록" tabIndex={0}><table className="data-table home-activity-table"><thead><tr>{['활동명', '팀장', '상태'].map(t => <th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{list.map(w => {
        const participating = member(w, s.userId), pending = w.applicantIds?.includes(s.userId), closed = ['완료', '보관'].includes(w.status);
        return <tr key={w.id}><td><button className="workspace-name-cell home-activity-name" onClick={() => open({ kind: 'workspace-info', workspaceId: w.id })}><span className={`workspace-initial ${w.type}`}>{w.initial}</span><span><strong>{w.name}</strong><small>{w.type === 'study' ? '스터디' : '프로젝트'} · {w.field} · {w.memberIds.length}명</small><span className={`tag ${participating ? 'mine' : 'external'}`}>{participating ? '참여 중' : pending ? '신청 대기' : '미참여'}</span></span></button></td><td>{name(w.leaderId)}</td><td><span className="home-status">{w.status}</span>{participating ? <a className="button quiet small" href={url(w)}>활동 열기 <Icon name="right" /></a> : <button className="button small" disabled={pending || closed} onClick={() => open({ kind: 'workspace-apply', workspaceId: w.id })}>{pending ? '신청 대기' : closed ? '신청 마감' : '참가 신청'}</button>}</td></tr>;
      })}</tbody></table>{!list.length && <Empty>조건에 맞는 활동이 없습니다.<br />검색어나 필터를 변경해주세요.</Empty>}</div>
    </section>
    <aside className="home-side" aria-label="나의 활동 요약">
      <section className="home-panel home-profile" aria-labelledby="home-profile-title"><div className="home-profile-main"><span className="home-profile-avatar"><Icon name="user" /></span><div className="home-profile-info"><h2 id="home-profile-title">{name(s.userId)}<span>님</span></h2><p>{s.officer ? '동아리 임원진' : 'CERT-IS 부원'}</p><a href="#/settings" className="note-line">내 정보 관리 <Icon name="right" /></a></div><button className="button quiet small" onClick={logout}>로그아웃</button></div><div className="home-profile-stats"><div><strong>{joined.filter(w => w.type === 'project').length}</strong><span>참여 프로젝트</span></div><div><strong>{joined.filter(w => w.type === 'study').length}</strong><span>참여 스터디</span></div><div><strong>{deadlines.length}</strong><span>남은 일정·마감</span></div></div><div className="home-profile-links"><a href="#/calendar"><Icon name="calendar" />내 캘린더</a><a href="#/reservation"><Icon name="reservation" />동아리방 예약</a></div></section>
      <section className="home-panel home-deadlines" aria-labelledby="home-deadline-title"><header className="home-panel-heading"><div><span className="home-eyebrow">UPCOMING</span><h2 id="home-deadline-title">D-day</h2></div><span className="note-line">가까운 마감부터</span></header><div className="home-deadline-filter"><label htmlFor="deadline-activity">활동</label><select id="deadline-activity" value={deadlineActivity} onChange={e => setDeadlineActivity(e.target.value)}><option value="all">전체 활동</option><option value="club">동아리 전체</option>{m.workspaces.filter(w => canView(w, s)).map(w => <option key={w.id} value={String(w.id)}>{w.name}</option>)}</select></div><div className="home-deadline-scroll" role="region" aria-label="D-day 목록" tabIndex={0}>{filtered.map(d => <button className="home-deadline" key={d.key} onClick={() => open(d.eventId !== undefined ? { kind: 'event', id: d.eventId, workspaceId: d.workspaceId ?? undefined } : { kind: 'workspace-info', workspaceId: d.workspaceId! })}><span className={`home-dday ${d.days <= 3 ? 'urgent' : ''}`}>{d.days === 0 ? 'D-day' : d.days < 0 ? `D+${Math.abs(d.days)}` : `D-${d.days}`}</span><span className="home-deadline-detail"><small>{d.activity}</small><strong>{d.title}</strong><span>{d.date}{d.days < 0 ? ' · 기한 지남' : ''}</span></span><Icon name="right" /></button>)}{!filtered.length && <Empty>예정된 일정이나 마감이 없습니다.</Empty>}</div></section>
    </aside>
  </div>;
}
export function EventRow({ event: e, open, pinned = false, onPin }: { event: CalendarEvent; open: ViewProps['open']; pinned?: boolean; onPin?: () => void }) {
  return <div className="event-row-with-pin" data-event-id={e.id}><button className="event-row" onClick={() => open(e.bookingId !== undefined ? { kind: 'booking-info', id: e.bookingId } : { kind: 'event', id: e.id, workspaceId: e.workspaceId ?? undefined })}><strong>{e.title}</strong><span>{e.date} {e.start}~{e.end}{e.endDate !== e.date && ` · ${e.endDate}까지`} · {e.status}</span><small>{e.assigneeIds.map(name).join(', ')} · {e.work || '담당업무 미지정'}</small></button>{onPin && <button type="button" className={`icon-button event-pin ${pinned ? 'pinned' : ''}`} aria-pressed={pinned} aria-label={`${e.title} 즐겨찾기 ${pinned ? '해제' : '추가'}`} title={`즐겨찾기 ${pinned ? '해제' : '추가'}`} onClick={onPin}><Icon name="pin" /></button>}</div>;
}
export function Calendar({ model: m, session: s, prefs: p, setPrefs, open, activity: w }: ViewProps & { activity?: Workspace }) {
  const [month, setMonth] = useState(() => new Date(`${today()}T12:00:00`).getMonth()), [year, setYear] = useState(() => Number(today().slice(0, 4))), [day, setDay] = useState(today);
  const dayDetails = useRef<HTMLElement>(null);
  function selectDay(value: string) { setDay(value); dayDetails.current?.scrollIntoView({ block: 'nearest' }); }
  const pins = !w ? p.calendarPins[s.userId] || [] : [], pinned = (e: CalendarEvent) => pins.includes(String(e.id));
  const order = (a: CalendarEvent, b: CalendarEvent) => Number(pinned(b)) - Number(pinned(a)) || a.start.localeCompare(b.start);
  const events = calendarEvents(m, s, w, w ? p.calendarMine : false, p.calendarScope).filter(e => !!w || !p.calendarMine || e.assigneeIds.includes(s.userId) || pinned(e));
  function togglePin(e: CalendarEvent) { const id = String(e.id); setPrefs({ calendarPins: { ...p.calendarPins, [s.userId]: pinned(e) ? pins.filter(x => x !== id) : [...pins, id] } }); }
  const eventRow = (e: CalendarEvent) => <EventRow key={e.id} event={e} open={open} pinned={pinned(e)} onPin={!w ? () => togglePin(e) : undefined} />;
  const first = new Date(year, month, 1, 12), start = new Date(first); start.setDate(1 - (first.getDay() + 6) % 7);
  const weeks = Math.ceil(((first.getDay() + 6) % 7 + new Date(year, month + 1, 0).getDate()) / 7);
  const changeMonth = (offset: number) => { const date = new Date(year, month + offset, 1, 12); setMonth(date.getMonth()); setYear(date.getFullYear()); setDay(dateString(date)); };
  return <div className={`calendar-view ${!w ? 'personal-calendar' : ''}`}>{!w && <Heading title="개인 캘린더" />}<div className="toolbar"><div className="month-heading"><IconButton title="이전 달" icon="left" onClick={() => changeMonth(-1)} /><h2>{year}.{String(month + 1).padStart(2, '0')}</h2><IconButton title="다음 달" icon="right" onClick={() => changeMonth(1)} /><button className="button quiet small" onClick={() => { const date = dateObj(today()); setMonth(date.getMonth()); setYear(date.getFullYear()); setDay(today()); }}>오늘</button></div><div className="toolbar-group"><button className="button small" onClick={() => setPrefs({ calendarMode: p.calendarMode === 'month' ? 'list' : 'month' })}>{p.calendarMode === 'month' ? '목록 보기' : '월간 보기'}</button><IconButton title="일정 표시 조건" icon="filter" onClick={() => open({ kind: 'calendar-filters', workspaceId: w?.id })} />{(!w || writable(w, s)) && <IconButton title="일정 등록" icon="plus" onClick={() => open({ kind: 'event', workspaceId: w?.id, date: day })} />}</div></div><p className="note-line">{p.calendarMine ? '내 담당 일정' : '팀 전체 일정'}{!w && s.officer && p.calendarScope === 'all' && ' · 전체 활동 운영 조회'}{!w ? ' · 날짜를 선택해 여러 일정을 핀으로 표시 · 즐겨찾기는 항상 표시' : ' · 날짜를 선택하면 전체 일정 표시'}</p>
    {p.calendarMode === 'list' ? <div className="event-list">{events.filter(e => e.date.slice(0, 7) === `${year}-${String(month + 1).padStart(2, '0')}`).sort((a, b) => a.date.localeCompare(b.date) || order(a, b)).map(eventRow)}{!events.some(e => e.date.slice(0, 7) === `${year}-${String(month + 1).padStart(2, '0')}`) && <Empty>이번 달 일정 없음</Empty>}</div> : <div className="calendar-layout"><div className="month-calendar" style={{ '--weeks': weeks } as CSSProperties}>{['월', '화', '수', '목', '금', '토', '일'].map(t => <div className="weekday" key={t}>{t}</div>)}{Array.from({ length: weeks * 7 }, (_, i) => {
      const d = new Date(start); d.setDate(d.getDate() + i); const value = dateString(d), list = events.filter(e => e.date <= value && e.endDate >= value).sort(order);
      const favorites = list.filter(pinned), preview = w ? list.slice(0, 1) : [...favorites, ...list.filter(e => !pinned(e)).slice(0, Math.max(0, 2 - favorites.length))], hidden = list.length - preview.length;
      return <div key={value} data-date={value} className={`calendar-day ${d.getMonth() !== month ? 'outside' : ''} ${value === day ? 'selected' : ''}`}><div className="calendar-day-heading"><button aria-label={`${value} 일정 ${list.length}개`} aria-pressed={value === day} className={`day-button ${value === today() ? 'today' : ''}`} onClick={() => selectDay(value)}>{d.getDate()}</button>{hidden > 0 && <button className="calendar-count" aria-label={`${value} 나머지 일정 ${hidden}개 보기`} onClick={() => selectDay(value)}>+{hidden}</button>}</div>{preview.map(e => <button key={e.id} data-event-id={e.id} className={`calendar-event ${pinned(e) ? 'pinned' : ''} ${e.visibility === 'club' ? 'club' : e.assigneeIds.includes(s.userId) ? 'mine' : ''}`} title={e.title} aria-label={`${e.title}${pinned(e) ? ' · 즐겨찾기' : ''}`} onClick={() => open(e.bookingId !== undefined ? { kind: 'booking-info', id: e.bookingId } : { kind: 'event', id: e.id, workspaceId: e.workspaceId ?? undefined })}>{pinned(e) && <Icon name="pin" />}{e.title}</button>)}</div>;
    })}</div><section ref={dayDetails} className="calendar-aside" aria-label="선택한 날짜 일정"><h3>{day}</h3>{events.filter(e => e.date <= day && e.endDate >= day).sort(order).map(eventRow)}{!events.some(e => e.date <= day && e.endDate >= day) && <p className="note-line">일정 없음</p>}</section></div>}
  </div>;
}
export function Reservations({ model: m, session: s, open, activity: w }: ViewProps & { activity?: Workspace }) {
  const [startDate, setStartDate] = useState(today), [days, setDays] = useState(28), board = useRef<HTMLDivElement>(null);
  const dates = Array.from({ length: days }, (_, i) => { const d = dateObj(startDate); d.setDate(d.getDate() + i); return dateString(d); });
  const active = m.bookings.filter(b => b.status !== '취소'), now = minutes(new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Seoul', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date()));
  function jump(value: string) { if (!value || Number.isNaN(dateObj(value).valueOf()) || dateString(dateObj(value)) !== value) return; setStartDate(value); setDays(28); board.current?.scrollTo({ top: 0 }); }
  // ponytail: append two weeks at a time; virtualize rows if long sessions make rendering slow.
  return <>{!w && <Heading title="동아리방 예약" />}<div className="toolbar"><div className="toolbar-group"><label className="reservation-date-picker">시작 날짜 <input type="date" aria-label="예약 시작 날짜" value={startDate} onChange={e => jump(e.target.value)} /></label><button className="button quiet small" onClick={() => jump(today())}>오늘</button></div>{(!w || writable(w, s)) && <IconButton title="예약 신청" icon="plus" onClick={() => open({ kind: 'booking', workspaceId: w?.id })} />}</div><p className="note-line">09:00~24:00 · 30분 단위 · 빈 칸은 예약 신청, 예약 구간은 상세 확인</p><div ref={board} className="reservation-board-wrap" role="region" aria-label="날짜별 예약 시간표" tabIndex={0} onScroll={e => { const el = e.currentTarget; if (el.scrollHeight - el.scrollTop - el.clientHeight < 160) setDays(count => count + 14); }}><div className="reservation-board"><div className="reservation-time-row"><div className="reservation-head reservation-corner">날짜</div>{Array.from({ length: 15 }, (_, i) => <div className="reservation-head time-label" key={i}>{String(9 + i).padStart(2, '0')}{i === 14 && <span className="time-end">24</span>}</div>)}</div>{dates.map((d, index) => <Fragment key={d}>{(index === 0 || d.slice(0, 7) !== dates[index - 1].slice(0, 7)) && <div className="reservation-month-divider" role="separator" aria-label={`${d.slice(0, 4)}년 ${Number(d.slice(5, 7))}월`}><span>{d.slice(0, 4)}년 {Number(d.slice(5, 7))}월</span></div>}<div className={`reservation-day-row ${d === today() ? 'today' : ''}`} data-date={d} key={d}><div className="reservation-date" title={d}><strong>{Number(d.slice(8))}({['일', '월', '화', '수', '목', '금', '토'][dateObj(d).getDay()]})</strong></div>{bookingStarts.map(start => {
      const minute = minutes(start), b = active.find(b => b.date === d && minutes(b.start) <= minute && bookingEndMinutes(b.end) > minute);
      if (b && minutes(b.start) !== minute) return null;
      const full = b && (member(workspace(m, b.workspaceId), s.userId) || s.officer), title = b ? `${d} ${b.start}~${b.end} · ${name(b.ownerId)}${full ? ` · ${workspace(m, b.workspaceId)?.name}` : ''}` : `${d} ${time(minute)}~${time(minute + 30)} 예약 신청`;
      return <button key={minute} data-start={time(minute)} className={`booking-slot ${minute % 60 === 0 ? 'hour-start' : ''} ${b ? 'occupied' : ''} ${b && member(workspace(m, b.workspaceId), s.userId) ? 'mine' : ''}`} style={b ? { gridColumn: `span ${(bookingEndMinutes(b.end) - minute) / 30}` } : undefined} title={title} aria-label={title} disabled={!b && (d < today() || d === today() && minute <= now || !!w && !writable(w, s))} onClick={() => open(b ? { kind: 'booking-info', id: b.id } : { kind: 'booking', workspaceId: w?.id, date: d, start: time(minute) })}>{b && name(b.ownerId)}</button>;
    })}</div></Fragment>)}</div><button className="reservation-more button quiet small" onClick={() => setDays(count => count + 14)}>다음 14일 보기</button></div><section className="reservation-aside"><h3>{w ? '이 활동 예약' : '내 활동 예약'} · 취소 기록 포함</h3><div className="booking-list">{m.bookings.filter(b => w ? same(b.workspaceId, w.id) : member(workspace(m, b.workspaceId), s.userId) || s.officer).sort((a, b) => a.date.localeCompare(b.date)).map(b => <button className="event-row" key={b.id} onClick={() => open({ kind: 'booking-info', id: b.id })}><strong>{b.purpose || workspace(m, b.workspaceId)?.name} · {b.status}</strong><span>{b.date} {b.start}~{b.end} · {name(b.ownerId)}</span></button>)}</div></section></>;
}
export function Settings({ model: m, session: s, prefs: p, setPrefs, open, notify }: ViewProps) {
  function simulate() {
    try { const w = workspace(m, p.chatWorkspaceId); requireMember(w, s); const rooms = m.rooms.filter(r => same(r.workspaceId, w.id) && r.memberIds.includes(s.userId) && !r.archived), r = rooms.find(r => same(r.id, p.chatRooms[w.id])) || rooms.at(-1), other = r?.memberIds.find(x => x !== s.userId); if (!r || !other) throw new Error('다른 참여자가 있는 방이 필요함'); mutate('수신 예시', { ...s, userId: other }, next => { room(next, r.id)!.messages.push({ id: id('msg'), authorId: other, createdAt: iso(), text: '수신 예시: 현재 작업을 유지하면서 새 대화를 확인할 수 있음' }); }); notify('수신 예시 추가됨'); } catch (error) { notify((error as Error).message); }
  }
  return <><Heading title="설정" /><section className="settings-block"><div className="settings-row"><div><h2>사용자 미리보기</h2><p>{name(s.userId)} · {s.officer ? '임원진' : '일반 부원'} · 팀장은 활동별 관계로 결정됨</p></div><button className="button small" onClick={() => open({ kind: 'profile' })}>변경</button></div></section><section className="settings-block"><div className="settings-row"><div><h2>화면 설정</h2><p>채팅 폭과 최근 방, 접기 상태를 이 브라우저에 보관함</p></div><button className="button small" onClick={() => setPrefs({ chatWidth: 300, collapsed: false })}>초기화</button></div></section><section className="settings-block"><div className="settings-row"><div><h2>대화 수신 예시</h2><p>실시간 연결 없이 스크롤·미확인 표시를 점검하는 도구임</p></div><button className="button small" onClick={simulate}>메시지 추가</button></div></section><section className="settings-block"><div className="settings-row"><div><h2>샘플 데이터</h2><p>예약·일정·문서·활동·초안을 초기화함</p></div><button className="button danger small" onClick={() => open({ kind: 'reset' })}>초기화</button></div></section><section className="settings-block"><h2>최근 변경</h2>{m.audit.slice(0, 12).map(a => <p className="note-line" key={a.id}>{stamp(a.at)} · {name(a.userId)} · {a.action}</p>)}{!m.audit.length && <p className="note-line">변경 기록 없음</p>}</section></>;
}
