import { Fragment, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import type { Event, Workspace } from './model';
import { bookingEndMinutes, bookingStarts, canView, dateObj, dateString, fields, id, iso, member, minutes, mutate, name, requireMember, role, room, same, stamp, time, today, url, visibleEvents, workspace, writable } from './model';
import { Empty, Heading, Icon, IconButton } from './ui';
import type { ViewProps } from './ui';

export function Dashboard({ model: m, session: s, prefs: p, setPrefs, open }: ViewProps) {
  const [query, setQuery] = useState('');
  const list = m.workspaces.filter(w => canView(w, s) && (s.officer && p.scope === 'all' || member(w, s.userId)) && w.name.includes(query) && (p.listType === 'all' || w.type === p.listType) && (p.listField === 'all' || w.field === p.listField) && (p.listOwner === 'all' || w.leaderId === p.listOwner) && (p.listStatus === 'all' || (p.listStatus === 'active' ? !['완료', '보관'].includes(w.status) : w.status === p.listStatus))).sort((a, b) => p.listOrder === 'name' ? a.name.localeCompare(b.name, 'ko') : p.listOrder === 'deadline' ? (a.endDate || '9999').localeCompare(b.endDate || '9999') : b.updatedAt.localeCompare(a.updatedAt));
  return <><Heading title="활동">{s.officer && <button className="button small" onClick={() => setPrefs({ scope: p.scope === 'all' ? 'mine' : 'all' })}>{p.scope === 'all' ? '전체 활동' : '내 활동'}</button>}<IconButton title="활동 생성" icon="plus" onClick={() => open({ kind: 'workspace-new' })} /></Heading><div className="toolbar"><div className="toolbar-group"><input className="filter-input" placeholder="활동 검색" aria-label="활동 검색" value={query} onChange={e => setQuery(e.target.value)} /><IconButton title="필터 및 정렬" icon="filter" onClick={() => open({ kind: 'list-filters' })} /><button className="button quiet small" onClick={() => { setQuery(''); setPrefs({ listType: 'all', listField: 'all', listStatus: 'active', listOwner: 'all', listOrder: 'recent' }); }}>초기화</button></div><span className="note-line">{list.length}개 · {s.officer && p.scope === 'all' ? '전체 조회' : '참여 활동'}</span></div><div className="table-wrap"><table className="data-table"><thead><tr>{['활동', '팀장', '내 역할', '상태', '다음 일정 / 마감'].map(t => <th key={t}>{t}</th>)}</tr></thead><tbody>{list.map(w => { const next = visibleEvents(m, s, w).filter(e => same(e.workspaceId, w.id) && e.date >= today() && e.status !== '완료').sort((a, b) => a.date.localeCompare(b.date))[0]; return <tr key={w.id}><td><a className="workspace-name-cell" href={url(w)}><span className={`workspace-initial ${w.type}`}>{w.initial}</span><span>{w.name}<small>{w.type === 'study' ? '스터디' : '프로젝트'} · {w.field} · {w.memberIds.length}명</small></span></a></td><td>{name(w.leaderId)}</td><td>{role(w, s)}</td><td>{w.status}</td><td>{next ? `${next.date} · ${next.title}` : w.endDate ? `${w.endDate} 마감` : '—'}</td></tr>; })}</tbody></table></div>{!list.length && <Empty>참여 활동이 없거나 조건에 맞지 않음. 조건 초기화 또는 활동 생성으로 시작하면 됨</Empty>}</>;
}
export function EventRow({ event: e, open, pinned = false, onPin }: { event: Event; open: ViewProps['open']; pinned?: boolean; onPin?: () => void }) {
  return <div className="event-row-with-pin" data-event-id={e.id}><button className="event-row" onClick={() => open({ kind: 'event', id: e.id, workspaceId: e.workspaceId ?? undefined })}><strong>{e.title}</strong><span>{e.date} {e.start}~{e.end}{e.endDate !== e.date && ` · ${e.endDate}까지`} · {e.status}</span><small>{e.assigneeIds.map(name).join(', ')} · {e.work || '담당업무 미지정'}</small></button>{onPin && <button type="button" className={`icon-button event-pin ${pinned ? 'pinned' : ''}`} aria-pressed={pinned} aria-label={`${e.title} 즐겨찾기 ${pinned ? '해제' : '추가'}`} title={`즐겨찾기 ${pinned ? '해제' : '추가'}`} onClick={onPin}><Icon name="pin" /></button>}</div>;
}
export function Calendar({ model: m, session: s, prefs: p, setPrefs, open, activity: w }: ViewProps & { activity?: Workspace }) {
  const [month, setMonth] = useState(() => new Date(`${today()}T12:00:00`).getMonth()), [year, setYear] = useState(() => Number(today().slice(0, 4))), [day, setDay] = useState(today);
  const dayDetails = useRef<HTMLElement>(null);
  function selectDay(value: string) { setDay(value); dayDetails.current?.scrollIntoView({ block: 'nearest' }); }
  const pins = !w ? p.calendarPins[s.userId] || [] : [], pinned = (e: Event) => pins.includes(String(e.id));
  const order = (a: Event, b: Event) => Number(pinned(b)) - Number(pinned(a)) || a.start.localeCompare(b.start);
  const events = visibleEvents(m, s, w, w ? p.calendarMine : false, p.calendarScope).filter(e => !!w || !p.calendarMine || e.assigneeIds.includes(s.userId) || pinned(e));
  function togglePin(e: Event) { const id = String(e.id); setPrefs({ calendarPins: { ...p.calendarPins, [s.userId]: pinned(e) ? pins.filter(x => x !== id) : [...pins, id] } }); }
  const eventRow = (e: Event) => <EventRow key={e.id} event={e} open={open} pinned={pinned(e)} onPin={!w ? () => togglePin(e) : undefined} />;
  const first = new Date(year, month, 1, 12), start = new Date(first); start.setDate(1 - (first.getDay() + 6) % 7);
  const weeks = Math.ceil(((first.getDay() + 6) % 7 + new Date(year, month + 1, 0).getDate()) / 7);
  const changeMonth = (offset: number) => { const date = new Date(year, month + offset, 1, 12); setMonth(date.getMonth()); setYear(date.getFullYear()); setDay(dateString(date)); };
  return <div className={`calendar-view ${!w ? 'personal-calendar' : ''}`}>{!w && <Heading title="개인 캘린더" />}<div className="toolbar"><div className="month-heading"><IconButton title="이전 달" icon="left" onClick={() => changeMonth(-1)} /><h2>{year}.{String(month + 1).padStart(2, '0')}</h2><IconButton title="다음 달" icon="right" onClick={() => changeMonth(1)} /><button className="button quiet small" onClick={() => { const date = dateObj(today()); setMonth(date.getMonth()); setYear(date.getFullYear()); setDay(today()); }}>오늘</button></div><div className="toolbar-group"><button className="button small" onClick={() => setPrefs({ calendarMode: p.calendarMode === 'month' ? 'list' : 'month' })}>{p.calendarMode === 'month' ? '목록 보기' : '월간 보기'}</button><IconButton title="일정 표시 조건" icon="filter" onClick={() => open({ kind: 'calendar-filters', workspaceId: w?.id })} />{(!w || writable(w, s)) && <IconButton title="일정 등록" icon="plus" onClick={() => open({ kind: 'event', workspaceId: w?.id, date: day })} />}</div></div><p className="note-line">{p.calendarMine ? '내 담당 일정' : '팀 전체 일정'}{!w && s.officer && p.calendarScope === 'all' && ' · 전체 활동 운영 조회'}{!w ? ' · 날짜를 선택해 여러 일정을 핀으로 표시 · 즐겨찾기는 항상 표시' : ' · 날짜를 선택하면 전체 일정 표시'}</p>
    {p.calendarMode === 'list' ? <div className="event-list">{events.filter(e => e.date.slice(0, 7) === `${year}-${String(month + 1).padStart(2, '0')}`).sort((a, b) => a.date.localeCompare(b.date) || order(a, b)).map(eventRow)}{!events.some(e => e.date.slice(0, 7) === `${year}-${String(month + 1).padStart(2, '0')}`) && <Empty>이번 달 일정 없음</Empty>}</div> : <div className="calendar-layout"><div className="month-calendar" style={{ '--weeks': weeks } as CSSProperties}>{['월', '화', '수', '목', '금', '토', '일'].map(t => <div className="weekday" key={t}>{t}</div>)}{Array.from({ length: weeks * 7 }, (_, i) => {
      const d = new Date(start); d.setDate(d.getDate() + i); const value = dateString(d), list = events.filter(e => e.date <= value && e.endDate >= value).sort(order);
      const favorites = list.filter(pinned), preview = w ? list.slice(0, 1) : [...favorites, ...list.filter(e => !pinned(e)).slice(0, Math.max(0, 2 - favorites.length))], hidden = list.length - preview.length;
      return <div key={value} data-date={value} className={`calendar-day ${d.getMonth() !== month ? 'outside' : ''} ${value === day ? 'selected' : ''}`}><div className="calendar-day-heading"><button aria-label={`${value} 일정 ${list.length}개`} aria-pressed={value === day} className={`day-button ${value === today() ? 'today' : ''}`} onClick={() => selectDay(value)}>{d.getDate()}</button>{hidden > 0 && <button className="calendar-count" aria-label={`${value} 나머지 일정 ${hidden}개 보기`} onClick={() => selectDay(value)}>+{hidden}</button>}</div>{preview.map(e => <button key={e.id} data-event-id={e.id} className={`calendar-event ${pinned(e) ? 'pinned' : ''} ${e.visibility === 'club' ? 'club' : e.assigneeIds.includes(s.userId) ? 'mine' : ''}`} title={e.title} aria-label={`${e.title}${pinned(e) ? ' · 즐겨찾기' : ''}`} onClick={() => open({ kind: 'event', id: e.id, workspaceId: e.workspaceId ?? undefined })}>{pinned(e) && <Icon name="pin" />}{e.title}</button>)}</div>;
    })}</div><section ref={dayDetails} className="calendar-aside" aria-label="선택한 날짜 일정"><h3>{day}</h3>{events.filter(e => e.date <= day && e.endDate >= day).sort(order).map(eventRow)}{!events.some(e => e.date <= day && e.endDate >= day) && <p className="note-line">일정 없음</p>}</section></div>}
  </div>;
}
export function Reservations({ model: m, session: s, open, activity: w }: ViewProps & { activity?: Workspace }) {
  const [startDate, setStartDate] = useState(today), [days, setDays] = useState(28), board = useRef<HTMLDivElement>(null);
  const dates = Array.from({ length: days }, (_, i) => { const d = dateObj(startDate); d.setDate(d.getDate() + i); return dateString(d); });
  const active = m.bookings.filter(b => b.status !== '취소'), now = minutes(new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Seoul', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date()));
  function jump(value: string) { if (!value || Number.isNaN(dateObj(value).valueOf()) || dateString(dateObj(value)) !== value) return; setStartDate(value); setDays(28); board.current?.scrollTo({ top: 0 }); }
  // ponytail: append two weeks at a time; virtualize rows if long sessions make rendering slow.
  return <>{!w && <Heading title="동아리방 예약" />}<div className="toolbar"><div className="toolbar-group"><label className="reservation-date-picker">시작 날짜 <input type="date" aria-label="예약 시작 날짜" value={startDate} onChange={e => jump(e.target.value)} /></label><button className="button quiet small" onClick={() => jump(today())}>오늘</button></div>{(!w || writable(w, s)) && <IconButton title="예약 신청" icon="plus" onClick={() => open({ kind: 'booking', workspaceId: w?.id })} />}</div><p className="note-line">09:00~24:00 · 30분 단위 · 빈 칸은 예약 신청, 예약 구간은 상세 확인</p><div ref={board} className="reservation-board-wrap" role="region" aria-label="날짜별 예약 시간표" tabIndex={0} onScroll={e => { const el = e.currentTarget; if (el.scrollHeight - el.scrollTop - el.clientHeight < 160) setDays(count => count + 14); }}><div className="reservation-board"><div className="reservation-time-row"><div className="reservation-head reservation-corner">날짜</div>{Array.from({ length: 15 }, (_, i) => <div className="reservation-head time-label" key={i}>{String(9 + i).padStart(2, '0')}{i === 14 && <span className="time-end">24</span>}</div>)}</div>{dates.map((d, index) => <Fragment key={d}>{(index === 0 || d.slice(0, 7) !== dates[index - 1].slice(0, 7)) && <div className="reservation-month-divider" role="separator" aria-label={`${d.slice(0, 4)}년 ${Number(d.slice(5, 7))}월`}><span>{d.slice(0, 4)}년 {Number(d.slice(5, 7))}월</span></div>}<div className={`reservation-day-row ${d === today() ? 'today' : ''}`} data-date={d} key={d}><div className="reservation-date" title={d}><strong>{Number(d.slice(8))}({['일', '월', '화', '수', '목', '금', '토'][dateObj(d).getDay()]})</strong></div>{bookingStarts.map(start => {
      const minute = minutes(start), b = active.find(b => b.date === d && minutes(b.start) <= minute && bookingEndMinutes(b.end) > minute);
      if (b && minutes(b.start) !== minute) return null;
      const full = b && (member(workspace(m, b.workspaceId), s.userId) || s.officer), title = b ? `${d} ${b.start}~${b.end} · ${name(b.ownerId)}${full ? ` · ${workspace(m, b.workspaceId)?.name}` : ''}` : `${d} ${time(minute)}~${time(minute + 30)} 예약 신청`;
      return <button key={minute} data-start={time(minute)} className={`booking-slot ${minute % 60 === 0 ? 'hour-start' : ''} ${b ? 'occupied' : ''} ${b && member(workspace(m, b.workspaceId), s.userId) ? 'mine' : ''}`} style={b ? { gridColumn: `span ${(bookingEndMinutes(b.end) - minute) / 30}` } : undefined} title={title} aria-label={title} disabled={!b && (d < today() || d === today() && minute <= now || !!w && !writable(w, s))} onClick={() => open(b ? { kind: 'booking-info', id: b.id } : { kind: 'booking', workspaceId: w?.id, date: d, start: time(minute) })}>{b && name(b.ownerId)}</button>;
    })}</div></Fragment>)}</div><button className="reservation-more button quiet small" onClick={() => setDays(count => count + 14)}>다음 14일 보기</button></div><section className="reservation-aside"><h3>{w ? '이 활동 예약' : '내 활동 예약'} · 취소 기록 포함</h3><div className="booking-list">{m.bookings.filter(b => w ? same(b.workspaceId, w.id) : member(workspace(m, b.workspaceId), s.userId) || s.officer).sort((a, b) => a.date.localeCompare(b.date)).map(b => <button className="event-row" key={b.id} onClick={() => open({ kind: 'booking-info', id: b.id })}><strong>{b.purpose || workspace(m, b.workspaceId)?.name} · {b.status}</strong><span>{b.date} {b.start}~{b.end} · {name(b.ownerId)}</span></button>)}</div></section></>;
}
export function AI({ model: m, session: s, prefs: p, setPrefs }: ViewProps) {
  const field = fields[p.aiField || 0];
  return <><Heading title="AI 추천" /><div className="ai-layout"><form onSubmit={e => { e.preventDefault(); setPrefs({ aiSubmitted: true }); }}><fieldset className="question"><legend>관심 분야</legend>{fields.map((text, i) => <label className="radio-choice" key={text}><input type="radio" name="field" checked={(p.aiField || 0) === i} onChange={() => setPrefs({ aiField: i, aiSubmitted: false })} />{text}</label>)}</fieldset><fieldset className="question"><legend>경험</legend>{['처음 시작', '기초 학습 경험', '프로젝트 경험'].map((text, i) => <label className="radio-choice" key={text}><input type="radio" name="experience" checked={(p.aiExperience || 0) === i} onChange={() => setPrefs({ aiExperience: i, aiSubmitted: false })} />{text}</label>)}</fieldset><button className="button primary">추천 보기</button></form><div className="ai-result"><span className="tag">응답 기반 샘플 · Gemini 미연결</span>{p.aiSubmitted ? <><h2>{field}</h2><p>{['기초 개념 학습과 작은 실습으로 시작하는 스터디를 추천함', '주제를 정한 실습과 결과 공유를 포함한 활동을 추천함', '실제 문제를 분석하고 산출물을 만드는 프로젝트를 추천함'][p.aiExperience || 0]}</p><div className="button-row">{m.workspaces.filter(w => canView(w, s) && w.field === field).map(w => <a key={w.id} className="button small" href={url(w)}>{w.name}</a>)}</div><button className="button quiet small" onClick={() => setPrefs({ aiSubmitted: false })}>다시 선택</button></> : <p>분야와 경험에 따라 다른 예시를 확인할 수 있음</p>}</div></div></>;
}
export function Settings({ model: m, session: s, prefs: p, setPrefs, open, notify }: ViewProps) {
  function simulate() {
    try { const w = workspace(m, p.chatWorkspaceId); requireMember(w, s); const rooms = m.rooms.filter(r => same(r.workspaceId, w.id) && r.memberIds.includes(s.userId) && !r.archived), r = rooms.find(r => same(r.id, p.chatRooms[w.id])) || rooms.at(-1), other = r?.memberIds.find(x => x !== s.userId); if (!r || !other) throw new Error('다른 참여자가 있는 방이 필요함'); mutate('수신 예시', { ...s, userId: other }, next => { room(next, r.id)!.messages.push({ id: id('msg'), authorId: other, createdAt: iso(), text: '수신 예시: 현재 작업을 유지하면서 새 대화를 확인할 수 있음' }); }); notify('수신 예시 추가됨'); } catch (error) { notify((error as Error).message); }
  }
  return <><Heading title="설정" /><section className="settings-block"><div className="settings-row"><div><h2>사용자 미리보기</h2><p>{name(s.userId)} · {s.officer ? '임원진' : '일반 부원'} · 팀장은 활동별 관계로 결정됨</p></div><button className="button small" onClick={() => open({ kind: 'profile' })}>변경</button></div></section><section className="settings-block"><div className="settings-row"><div><h2>화면 설정</h2><p>채팅 폭과 최근 방, 접기 상태를 이 브라우저에 보관함</p></div><button className="button small" onClick={() => setPrefs({ chatWidth: 300, collapsed: false })}>초기화</button></div></section><section className="settings-block"><div className="settings-row"><div><h2>대화 수신 예시</h2><p>실시간 연결 없이 스크롤·미확인 표시를 점검하는 도구임</p></div><button className="button small" onClick={simulate}>메시지 추가</button></div></section><section className="settings-block"><div className="settings-row"><div><h2>샘플 데이터</h2><p>예약·일정·문서·활동·초안을 초기화함</p></div><button className="button danger small" onClick={() => open({ kind: 'reset' })}>초기화</button></div></section><section className="settings-block"><h2>최근 변경</h2>{m.audit.slice(0, 12).map(a => <p className="note-line" key={a.id}>{stamp(a.at)} · {name(a.userId)} · {a.action}</p>)}{!m.audit.length && <p className="note-line">변경 기록 없음</p>}</section></>;
}
